In [1]:
import pandas as pd
sales_data = {
    'Store': ['Chennai','Chennai','Bangalore','Bangalore','Hyderabad',
              'Hyderabad','Chennai','Bangalore','Hyderabad','Chennai'],
    'Category': ['Electronics','Clothing','Electronics','Groceries','Clothing',
                 'Groceries','Groceries','Clothing','Electronics','Electronics'],
    'Year': [2023,2023,2023,2023,2023,2024,2024,2024,2024,2024],
    'Sales': [25000,18000,22000,15000,16000,21000,19000,17000,23000,26000]
}

df_sales = pd.DataFrame(sales_data)

In [2]:
df_sales.groupby('Store')['Sales'].sum()

Store
Bangalore    54000
Chennai      88000
Hyderabad    60000
Name: Sales, dtype: int64

In [3]:
df_sales.groupby('Category')['Sales'].mean()

Category
Clothing       17000.000000
Electronics    24000.000000
Groceries      18333.333333
Name: Sales, dtype: float64

In [4]:
df_sales.groupby('Year')['Sales'].sum()

Year
2023     96000
2024    106000
Name: Sales, dtype: int64

In [5]:
df_sales[df_sales['Year'] == 2024]

       Store     Category  Year  Sales
5  Hyderabad    Groceries  2024  21000
6    Chennai    Groceries  2024  19000
7  Bangalore     Clothing  2024  17000
8  Hyderabad  Electronics  2024  23000
9    Chennai  Electronics  2024  26000

In [6]:
df_sales.groupby('Store').get_group('Chennai')

     Store     Category  Year  Sales
0  Chennai  Electronics  2023  25000
1  Chennai     Clothing  2023  18000
6  Chennai    Groceries  2024  19000
9  Chennai  Electronics  2024  26000

In [7]:
students = pd.DataFrame({
    'student_id':[1,2,3,4,5],
    'Name':['Arun','Divya','Karthik','Meena','Rahul'],
    'course_id':['C1','C2','C3','C1','C2']
})

courses = pd.DataFrame({
    'course_id':['C1','C2','C3','C4'],
    'Course_Name':['Python','Data Science','Power BI','AI']
})

In [8]:
pd.merge(students, courses, on='course_id', how='inner')

   student_id     Name course_id   Course_Name
0           1     Arun        C1        Python
1           2    Divya        C2  Data Science
2           3  Karthik        C3      Power BI
3           4    Meena        C1        Python
4           5    Rahul        C2  Data Science

In [9]:
pd.merge(students, courses, on='course_id', how='left')

   student_id     Name course_id   Course_Name
0           1     Arun        C1        Python
1           2    Divya        C2  Data Science
2           3  Karthik        C3      Power BI
3           4    Meena        C1        Python
4           5    Rahul        C2  Data Science

In [10]:
outer_df = pd.merge(students, courses, on='course_id', how='outer')
print(outer_df)

# Check missing values
outer_df.isnull()

   student_id     Name course_id   Course_Name
0         1.0     Arun        C1        Python
1         4.0    Meena        C1        Python
2         2.0    Divya        C2  Data Science
3         5.0    Rahul        C2  Data Science
4         3.0  Karthik        C3      Power BI
5         NaN      NaN        C4            AI

   student_id   Name  course_id  Course_Name
0       False  False      False        False
1       False  False      False        False
2       False  False      False        False
3       False  False      False        False
4       False  False      False        False
5        True   True      False        False

In [11]:
pd.date_range(start='2025-03-01', periods=10, freq='D')

DatetimeIndex(['2025-03-01', '2025-03-02', '2025-03-03', '2025-03-04',
               '2025-03-05', '2025-03-06', '2025-03-07', '2025-03-08',
               '2025-03-09', '2025-03-10'],
              dtype='datetime64[ns]', freq='D')

In [12]:
pd.date_range(start='2025-03-01', periods=10, freq='M')

C:\Users\msiva\AppData\Local\Temp\ipykernel_22156\1871166803.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range(start='2025-03-01', periods=10, freq='M')

DatetimeIndex(['2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30',
               '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31',
               '2025-11-30', '2025-12-31'],
              dtype='datetime64[ns]', freq='ME')